name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn test
        env:
          CI: true
      - run: yarn run prepublish
      - name: Publish to npm
        run: yarn run publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
